version: '3.4'

services:
  athene:
    image: athene:v0.1
    build:
      context: .
      dockerfile: src/Athene.Inventory.Web/Dockerfile
    # volumes:
    #   - athene-data:/app/bin/Debug/netcoreapp2.0/
    # volumes:
    #   - ./src/Athene.Inventory.Web/Inventory.db:/app/Inventory.db:rw
    # environment:
    #   DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 'false'
    ports:
      - 5000:80
  mariadb:
    image: mariadb:10.1.35-bionic
    # restart: always
    volumes:
      - mariadb-data:/var/lib/mysql
    ports: 
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 328D59A2E4784A4E8FA9521A2DAB105C
volumes:
  mariadb-data:                       # Kompositions-interner Bezeichner (s. services:*:volumes)
# volumes:
#   athene-data:                       # Kompositions-interner Bezeichner (s. services:*:volumes)