name: Docker Image CI

on:
  push:
    branches:
    - master
    - release/*
    - build

jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker-compose build
